# Generated by Django 4.0.2 on 2022-02-21 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_rename_oredeitem_orederitem_product_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrederItem',
            new_name='OrderItem',
        ),
    ]
